---
- name: Converge
  hosts: landscape-server-2303
  roles:
    - role: server
      server_version: "23.03"

- name: Converge
  hosts: landscape-server-2404
  roles:
    - role: server
      server_version: "24.04"
