---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: landscape-server-2404
    box: bento/ubuntu-24.04
    cpus: 4
    memory: 4096
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
  ansible-lint
  flake8
