---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: landscape-storage-2303
    box: generic/ubuntu2204
  - name: landscape-storage-2310
    box: generic/ubuntu2204
provisioner:
  name: ansible
verifier:
  name: testinfra
lint: |
  yamllint .
  ansible-lint
  flake8
