---
galaxy_info:
  namespace: stdevel
  role_name: server
  author: Christian Stankowic
  description: Installs Ubuntu Landscape
  license: GPL-3.0-only

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - systemsmanagement
    - ubuntu
    - linux
    - canonical
    - landscape

dependencies: []
